# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/robotics-verse/projects/felix/catkin_ws/src/ROS_VisionControl/src/src/controller.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Controller(object):
    def setupUi(self, Controller):
        Controller.setObjectName("Controller")
        Controller.resize(600, 727)
        self.gridLayout_7 = QtWidgets.QGridLayout(Controller)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(Controller)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ledtForceZ = QtWidgets.QLineEdit(self.tab_1)
        self.ledtForceZ.setObjectName("ledtForceZ")
        self.gridLayout_5.addWidget(self.ledtForceZ, 1, 3, 1, 1)
        self.lblForceX = QtWidgets.QLabel(self.tab_1)
        self.lblForceX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblForceX.setObjectName("lblForceX")
        self.gridLayout_5.addWidget(self.lblForceX, 0, 1, 1, 1)
        self.lblForceZ = QtWidgets.QLabel(self.tab_1)
        self.lblForceZ.setAlignment(QtCore.Qt.AlignCenter)
        self.lblForceZ.setObjectName("lblForceZ")
        self.gridLayout_5.addWidget(self.lblForceZ, 0, 3, 1, 1)
        self.lblForceY = QtWidgets.QLabel(self.tab_1)
        self.lblForceY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblForceY.setObjectName("lblForceY")
        self.gridLayout_5.addWidget(self.lblForceY, 0, 2, 1, 1)
        self.lblToqueY = QtWidgets.QLabel(self.tab_1)
        self.lblToqueY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblToqueY.setObjectName("lblToqueY")
        self.gridLayout_5.addWidget(self.lblToqueY, 2, 2, 1, 1)
        self.ledtForceX = QtWidgets.QLineEdit(self.tab_1)
        self.ledtForceX.setObjectName("ledtForceX")
        self.gridLayout_5.addWidget(self.ledtForceX, 1, 1, 1, 1)
        self.lblToqueZ = QtWidgets.QLabel(self.tab_1)
        self.lblToqueZ.setAlignment(QtCore.Qt.AlignCenter)
        self.lblToqueZ.setObjectName("lblToqueZ")
        self.gridLayout_5.addWidget(self.lblToqueZ, 2, 3, 1, 1)
        self.lblToqueX = QtWidgets.QLabel(self.tab_1)
        self.lblToqueX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblToqueX.setObjectName("lblToqueX")
        self.gridLayout_5.addWidget(self.lblToqueX, 2, 1, 1, 1)
        self.lblForce = QtWidgets.QLabel(self.tab_1)
        self.lblForce.setAlignment(QtCore.Qt.AlignCenter)
        self.lblForce.setObjectName("lblForce")
        self.gridLayout_5.addWidget(self.lblForce, 1, 0, 1, 1)
        self.ledtForceY = QtWidgets.QLineEdit(self.tab_1)
        self.ledtForceY.setObjectName("ledtForceY")
        self.gridLayout_5.addWidget(self.ledtForceY, 1, 2, 1, 1)
        self.lblToque = QtWidgets.QLabel(self.tab_1)
        self.lblToque.setAlignment(QtCore.Qt.AlignCenter)
        self.lblToque.setObjectName("lblToque")
        self.gridLayout_5.addWidget(self.lblToque, 3, 0, 1, 1)
        self.ledtToqueX = QtWidgets.QLineEdit(self.tab_1)
        self.ledtToqueX.setObjectName("ledtToqueX")
        self.gridLayout_5.addWidget(self.ledtToqueX, 3, 1, 1, 1)
        self.ledtToqueY = QtWidgets.QLineEdit(self.tab_1)
        self.ledtToqueY.setObjectName("ledtToqueY")
        self.gridLayout_5.addWidget(self.ledtToqueY, 3, 2, 1, 1)
        self.ledtToqueZ = QtWidgets.QLineEdit(self.tab_1)
        self.ledtToqueZ.setObjectName("ledtToqueZ")
        self.gridLayout_5.addWidget(self.ledtToqueZ, 3, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.pbtnVisualizeConfimap = QtWidgets.QPushButton(self.tab_1)
        self.pbtnVisualizeConfimap.setObjectName("pbtnVisualizeConfimap")
        self.gridLayout_2.addWidget(self.pbtnVisualizeConfimap, 16, 0, 1, 1)
        self.pbtnStartUSStream = QtWidgets.QPushButton(self.tab_1)
        self.pbtnStartUSStream.setObjectName("pbtnStartUSStream")
        self.gridLayout_2.addWidget(self.pbtnStartUSStream, 10, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ledt_trajectory_file_to_write = QtWidgets.QLineEdit(self.tab_1)
        self.ledt_trajectory_file_to_write.setObjectName("ledt_trajectory_file_to_write")
        self.horizontalLayout_4.addWidget(self.ledt_trajectory_file_to_write)
        self.pbtnWriteCurrRobotPose = QtWidgets.QPushButton(self.tab_1)
        self.pbtnWriteCurrRobotPose.setObjectName("pbtnWriteCurrRobotPose")
        self.horizontalLayout_4.addWidget(self.pbtnWriteCurrRobotPose)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 19, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbtnSaveHome = QtWidgets.QPushButton(self.tab_1)
        self.pbtnSaveHome.setObjectName("pbtnSaveHome")
        self.verticalLayout_3.addWidget(self.pbtnSaveHome)
        self.pbtnSaveOut = QtWidgets.QPushButton(self.tab_1)
        self.pbtnSaveOut.setObjectName("pbtnSaveOut")
        self.verticalLayout_3.addWidget(self.pbtnSaveOut)
        self.pbtnGoHome = QtWidgets.QPushButton(self.tab_1)
        self.pbtnGoHome.setObjectName("pbtnGoHome")
        self.verticalLayout_3.addWidget(self.pbtnGoHome)
        self.pbtnGoOut = QtWidgets.QPushButton(self.tab_1)
        self.pbtnGoOut.setObjectName("pbtnGoOut")
        self.verticalLayout_3.addWidget(self.pbtnGoOut)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbtnConnect = QtWidgets.QPushButton(self.tab_1)
        self.pbtnConnect.setObjectName("pbtnConnect")
        self.horizontalLayout_2.addWidget(self.pbtnConnect)
        self.pbtnDisconnect = QtWidgets.QPushButton(self.tab_1)
        self.pbtnDisconnect.setObjectName("pbtnDisconnect")
        self.horizontalLayout_2.addWidget(self.pbtnDisconnect)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ledt_full_path_to_imf = QtWidgets.QLineEdit(self.tab_1)
        self.ledt_full_path_to_imf.setObjectName("ledt_full_path_to_imf")
        self.horizontalLayout_8.addWidget(self.ledt_full_path_to_imf)
        self.pbtnLoadSweep_imf = QtWidgets.QPushButton(self.tab_1)
        self.pbtnLoadSweep_imf.setObjectName("pbtnLoadSweep_imf")
        self.horizontalLayout_8.addWidget(self.pbtnLoadSweep_imf)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 12, 0, 1, 1)
        self.pbtn_test_rotation = QtWidgets.QPushButton(self.tab_1)
        self.pbtn_test_rotation.setObjectName("pbtn_test_rotation")
        self.gridLayout_2.addWidget(self.pbtn_test_rotation, 21, 0, 1, 1)
        self.pbtnAddPoint = QtWidgets.QPushButton(self.tab_1)
        self.pbtnAddPoint.setObjectName("pbtnAddPoint")
        self.gridLayout_2.addWidget(self.pbtnAddPoint, 6, 0, 1, 1)
        self.pbtnInitROS = QtWidgets.QPushButton(self.tab_1)
        self.pbtnInitROS.setObjectName("pbtnInitROS")
        self.gridLayout_2.addWidget(self.pbtnInitROS, 8, 0, 1, 1)
        self.pbtnStopUSStream = QtWidgets.QPushButton(self.tab_1)
        self.pbtnStopUSStream.setObjectName("pbtnStopUSStream")
        self.gridLayout_2.addWidget(self.pbtnStopUSStream, 9, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ledtSliceIndex = QtWidgets.QLineEdit(self.tab_1)
        self.ledtSliceIndex.setObjectName("ledtSliceIndex")
        self.horizontalLayout_13.addWidget(self.ledtSliceIndex)
        self.pbtnComputerConfiMap = QtWidgets.QPushButton(self.tab_1)
        self.pbtnComputerConfiMap.setObjectName("pbtnComputerConfiMap")
        self.horizontalLayout_13.addWidget(self.pbtnComputerConfiMap)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 14, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblPosAngle = QtWidgets.QLabel(self.tab_1)
        self.lblPosAngle.setObjectName("lblPosAngle")
        self.gridLayout.addWidget(self.lblPosAngle, 4, 0, 1, 1)
        self.lblPosZ = QtWidgets.QLabel(self.tab_1)
        self.lblPosZ.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPosZ.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPosZ.setObjectName("lblPosZ")
        self.gridLayout.addWidget(self.lblPosZ, 0, 3, 1, 1)
        self.lblPosRa = QtWidgets.QLabel(self.tab_1)
        self.lblPosRa.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPosRa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPosRa.setObjectName("lblPosRa")
        self.gridLayout.addWidget(self.lblPosRa, 2, 1, 1, 1)
        self.lblPosY = QtWidgets.QLabel(self.tab_1)
        self.lblPosY.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPosY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPosY.setObjectName("lblPosY")
        self.gridLayout.addWidget(self.lblPosY, 0, 2, 1, 1)
        self.lblPosDistance = QtWidgets.QLabel(self.tab_1)
        self.lblPosDistance.setObjectName("lblPosDistance")
        self.gridLayout.addWidget(self.lblPosDistance, 1, 0, 1, 1)
        self.lblPosX = QtWidgets.QLabel(self.tab_1)
        self.lblPosX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPosX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPosX.setObjectName("lblPosX")
        self.gridLayout.addWidget(self.lblPosX, 0, 1, 1, 1)
        self.ledtPosX = QtWidgets.QLineEdit(self.tab_1)
        self.ledtPosX.setObjectName("ledtPosX")
        self.gridLayout.addWidget(self.ledtPosX, 1, 1, 1, 1)
        self.ledtPosY = QtWidgets.QLineEdit(self.tab_1)
        self.ledtPosY.setObjectName("ledtPosY")
        self.gridLayout.addWidget(self.ledtPosY, 1, 2, 1, 1)
        self.ledtPosZ = QtWidgets.QLineEdit(self.tab_1)
        self.ledtPosZ.setObjectName("ledtPosZ")
        self.gridLayout.addWidget(self.ledtPosZ, 1, 3, 1, 1)
        self.lblPosRb = QtWidgets.QLabel(self.tab_1)
        self.lblPosRb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPosRb.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPosRb.setObjectName("lblPosRb")
        self.gridLayout.addWidget(self.lblPosRb, 2, 2, 1, 1)
        self.lblPosRc = QtWidgets.QLabel(self.tab_1)
        self.lblPosRc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPosRc.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPosRc.setObjectName("lblPosRc")
        self.gridLayout.addWidget(self.lblPosRc, 2, 3, 1, 1)
        self.ledtAngRa = QtWidgets.QLineEdit(self.tab_1)
        self.ledtAngRa.setObjectName("ledtAngRa")
        self.gridLayout.addWidget(self.ledtAngRa, 4, 1, 1, 1)
        self.ledtAngRb = QtWidgets.QLineEdit(self.tab_1)
        self.ledtAngRb.setObjectName("ledtAngRb")
        self.gridLayout.addWidget(self.ledtAngRb, 4, 2, 1, 1)
        self.ledtAngRc = QtWidgets.QLineEdit(self.tab_1)
        self.ledtAngRc.setObjectName("ledtAngRc")
        self.gridLayout.addWidget(self.ledtAngRc, 4, 3, 1, 1)
        self.pbtnExcuteCmd = QtWidgets.QPushButton(self.tab_1)
        self.pbtnExcuteCmd.setObjectName("pbtnExcuteCmd")
        self.gridLayout.addWidget(self.pbtnExcuteCmd, 5, 3, 1, 1)
        self.chbRecordWrench = QtWidgets.QCheckBox(self.tab_1)
        self.chbRecordWrench.setObjectName("chbRecordWrench")
        self.gridLayout.addWidget(self.chbRecordWrench, 5, 2, 1, 1)
        self.chbUpdateState = QtWidgets.QCheckBox(self.tab_1)
        self.chbUpdateState.setObjectName("chbUpdateState")
        self.gridLayout.addWidget(self.chbUpdateState, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.pbtnExecuteTrajectory = QtWidgets.QPushButton(self.tab_1)
        self.pbtnExecuteTrajectory.setObjectName("pbtnExecuteTrajectory")
        self.gridLayout_2.addWidget(self.pbtnExecuteTrajectory, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.pbtnGoFanStart = QtWidgets.QPushButton(self.tab_2)
        self.pbtnGoFanStart.setObjectName("pbtnGoFanStart")
        self.gridLayout_6.addWidget(self.pbtnGoFanStart, 3, 0, 1, 1)
        self.cmbFanStartRotationAxis = QtWidgets.QComboBox(self.tab_2)
        self.cmbFanStartRotationAxis.setEditable(False)
        self.cmbFanStartRotationAxis.setObjectName("cmbFanStartRotationAxis")
        self.cmbFanStartRotationAxis.addItem("")
        self.cmbFanStartRotationAxis.addItem("")
        self.gridLayout_6.addWidget(self.cmbFanStartRotationAxis, 2, 0, 1, 1)
        self.ledtFanStartAngle = QtWidgets.QLineEdit(self.tab_2)
        self.ledtFanStartAngle.setObjectName("ledtFanStartAngle")
        self.gridLayout_6.addWidget(self.ledtFanStartAngle, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmbFanMotionType = QtWidgets.QComboBox(self.tab_2)
        self.cmbFanMotionType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbFanMotionType.setEditable(False)
        self.cmbFanMotionType.setObjectName("cmbFanMotionType")
        self.cmbFanMotionType.addItem("")
        self.cmbFanMotionType.addItem("")
        self.verticalLayout.addWidget(self.cmbFanMotionType)
        self.cmbRotationAxis = QtWidgets.QComboBox(self.tab_2)
        self.cmbRotationAxis.setObjectName("cmbRotationAxis")
        self.cmbRotationAxis.addItem("")
        self.cmbRotationAxis.addItem("")
        self.verticalLayout.addWidget(self.cmbRotationAxis)
        self.cmbRotationStep = QtWidgets.QComboBox(self.tab_2)
        self.cmbRotationStep.setObjectName("cmbRotationStep")
        self.cmbRotationStep.addItem("")
        self.cmbRotationStep.addItem("")
        self.cmbRotationStep.addItem("")
        self.cmbRotationStep.addItem("")
        self.cmbRotationStep.addItem("")
        self.verticalLayout.addWidget(self.cmbRotationStep)
        self.pbtnFanMotion = QtWidgets.QPushButton(self.tab_2)
        self.pbtnFanMotion.setObjectName("pbtnFanMotion")
        self.verticalLayout.addWidget(self.pbtnFanMotion)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.VisionControl = QtWidgets.QWidget()
        self.VisionControl.setObjectName("VisionControl")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.VisionControl)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ledt_poses_file_path = QtWidgets.QLineEdit(self.VisionControl)
        self.ledt_poses_file_path.setObjectName("ledt_poses_file_path")
        self.gridLayout_4.addWidget(self.ledt_poses_file_path, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ledtSweepPath = QtWidgets.QLineEdit(self.VisionControl)
        self.ledtSweepPath.setInputMask("")
        self.ledtSweepPath.setText("")
        self.ledtSweepPath.setObjectName("ledtSweepPath")
        self.horizontalLayout_6.addWidget(self.ledtSweepPath)
        self.ledtDownsamplingParam = QtWidgets.QLineEdit(self.VisionControl)
        self.ledtDownsamplingParam.setObjectName("ledtDownsamplingParam")
        self.horizontalLayout_6.addWidget(self.ledtDownsamplingParam)
        self.pbtnDownsampleSweep = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnDownsampleSweep.setObjectName("pbtnDownsampleSweep")
        self.horizontalLayout_6.addWidget(self.pbtnDownsampleSweep)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 12, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbtnForceMode = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnForceMode.setObjectName("pbtnForceMode")
        self.horizontalLayout_3.addWidget(self.pbtnForceMode)
        self.pbtnPositionMode = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnPositionMode.setObjectName("pbtnPositionMode")
        self.horizontalLayout_3.addWidget(self.pbtnPositionMode)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ledtMainDir = QtWidgets.QLineEdit(self.VisionControl)
        self.ledtMainDir.setObjectName("ledtMainDir")
        self.horizontalLayout_9.addWidget(self.ledtMainDir)
        self.pbtnCreateUSForLabelsWithoutStich = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnCreateUSForLabelsWithoutStich.setObjectName("pbtnCreateUSForLabelsWithoutStich")
        self.horizontalLayout_9.addWidget(self.pbtnCreateUSForLabelsWithoutStich)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 13, 0, 1, 1)
        self.pbtnContinueScan = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnContinueScan.setObjectName("pbtnContinueScan")
        self.gridLayout_4.addWidget(self.pbtnContinueScan, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pbtnExecScan = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnExecScan.setObjectName("pbtnExecScan")
        self.horizontalLayout_5.addWidget(self.pbtnExecScan)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.pbtnGoIntiPos = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnGoIntiPos.setObjectName("pbtnGoIntiPos")
        self.gridLayout_4.addWidget(self.pbtnGoIntiPos, 2, 0, 1, 1)
        self.pbtnReadPosesFromFile = QtWidgets.QPushButton(self.VisionControl)
        self.pbtnReadPosesFromFile.setObjectName("pbtnReadPosesFromFile")
        self.gridLayout_4.addWidget(self.pbtnReadPosesFromFile, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ledtStiffness = QtWidgets.QLineEdit(self.VisionControl)
        self.ledtStiffness.setObjectName("ledtStiffness")
        self.gridLayout_3.addWidget(self.ledtStiffness, 2, 0, 1, 1)
        self.ledtDesiredForce = QtWidgets.QLineEdit(self.VisionControl)
        self.ledtDesiredForce.setObjectName("ledtDesiredForce")
        self.gridLayout_3.addWidget(self.ledtDesiredForce, 2, 1, 1, 1)
        self.lblStiffness = QtWidgets.QLabel(self.VisionControl)
        self.lblStiffness.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStiffness.setObjectName("lblStiffness")
        self.gridLayout_3.addWidget(self.lblStiffness, 0, 0, 1, 1)
        self.lblSesiredForce = QtWidgets.QLabel(self.VisionControl)
        self.lblSesiredForce.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSesiredForce.setObjectName("lblSesiredForce")
        self.gridLayout_3.addWidget(self.lblSesiredForce, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rbtn_no_fine_tuning = QtWidgets.QRadioButton(self.VisionControl)
        self.rbtn_no_fine_tuning.setObjectName("rbtn_no_fine_tuning")
        self.verticalLayout_6.addWidget(self.rbtn_no_fine_tuning)
        self.rbtn_fine_tuning_1 = QtWidgets.QRadioButton(self.VisionControl)
        self.rbtn_fine_tuning_1.setObjectName("rbtn_fine_tuning_1")
        self.verticalLayout_6.addWidget(self.rbtn_fine_tuning_1)
        self.rbtn_both_fine_tunings = QtWidgets.QRadioButton(self.VisionControl)
        self.rbtn_both_fine_tunings.setObjectName("rbtn_both_fine_tunings")
        self.verticalLayout_6.addWidget(self.rbtn_both_fine_tunings)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.checkBox_include_whole_sweep = QtWidgets.QCheckBox(self.VisionControl)
        self.checkBox_include_whole_sweep.setObjectName("checkBox_include_whole_sweep")
        self.horizontalLayout_7.addWidget(self.checkBox_include_whole_sweep)
        self.ledtDataDir = QtWidgets.QLineEdit(self.VisionControl)
        self.ledtDataDir.setObjectName("ledtDataDir")
        self.horizontalLayout_7.addWidget(self.ledtDataDir)
        self.pbtn_stitching = QtWidgets.QPushButton(self.VisionControl)
        self.pbtn_stitching.setObjectName("pbtn_stitching")
        self.horizontalLayout_7.addWidget(self.pbtn_stitching)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 15, 0, 1, 1)
        self.tabWidget.addTab(self.VisionControl, "")
        self.US_preprocessing = QtWidgets.QWidget()
        self.US_preprocessing.setObjectName("US_preprocessing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.US_preprocessing)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbtnSavePose = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnSavePose.setObjectName("pbtnSavePose")
        self.verticalLayout_4.addWidget(self.pbtnSavePose)
        self.pbtnRoutePlanning = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnRoutePlanning.setObjectName("pbtnRoutePlanning")
        self.verticalLayout_4.addWidget(self.pbtnRoutePlanning)
        self.pbtnPrepareForScan = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnPrepareForScan.setObjectName("pbtnPrepareForScan")
        self.verticalLayout_4.addWidget(self.pbtnPrepareForScan)
        self.pbtnRunUSScan = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnRunUSScan.setObjectName("pbtnRunUSScan")
        self.verticalLayout_4.addWidget(self.pbtnRunUSScan)
        self.ledtSweepFilePath = QtWidgets.QLineEdit(self.US_preprocessing)
        self.ledtSweepFilePath.setObjectName("ledtSweepFilePath")
        self.verticalLayout_4.addWidget(self.ledtSweepFilePath)
        self.pbtnLoadSweepPosition = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnLoadSweepPosition.setObjectName("pbtnLoadSweepPosition")
        self.verticalLayout_4.addWidget(self.pbtnLoadSweepPosition)
        self.pbtnLoadSweepImage = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnLoadSweepImage.setObjectName("pbtnLoadSweepImage")
        self.verticalLayout_4.addWidget(self.pbtnLoadSweepImage)
        self.pbtnShowSurface = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnShowSurface.setObjectName("pbtnShowSurface")
        self.verticalLayout_4.addWidget(self.pbtnShowSurface)
        self.pbtnExtractBoneSurface = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnExtractBoneSurface.setObjectName("pbtnExtractBoneSurface")
        self.verticalLayout_4.addWidget(self.pbtnExtractBoneSurface)
        self.pbtbGetUSPointCloud = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtbGetUSPointCloud.setObjectName("pbtbGetUSPointCloud")
        self.verticalLayout_4.addWidget(self.pbtbGetUSPointCloud)
        self.pbtnReplaceWithLabel = QtWidgets.QPushButton(self.US_preprocessing)
        self.pbtnReplaceWithLabel.setObjectName("pbtnReplaceWithLabel")
        self.verticalLayout_4.addWidget(self.pbtnReplaceWithLabel)
        self.tabWidget.addTab(self.US_preprocessing, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Controller)
        self.tabWidget.setCurrentIndex(0)
        self.cmbRotationStep.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Controller)

    def retranslateUi(self, Controller):
        _translate = QtCore.QCoreApplication.translate
        Controller.setWindowTitle(_translate("Controller", "Form"))
        self.lblForceX.setText(_translate("Controller", "FX"))
        self.lblForceZ.setText(_translate("Controller", "FZ"))
        self.lblForceY.setText(_translate("Controller", "FY"))
        self.lblToqueY.setText(_translate("Controller", "TY"))
        self.lblToqueZ.setText(_translate("Controller", "TZ"))
        self.lblToqueX.setText(_translate("Controller", "TX"))
        self.lblForce.setText(_translate("Controller", "Force(N)"))
        self.lblToque.setText(_translate("Controller", "Toque(XX)"))
        self.pbtnVisualizeConfimap.setText(_translate("Controller", "Visualize Confimap"))
        self.pbtnStartUSStream.setText(_translate("Controller", "Start US Stream"))
        self.ledt_trajectory_file_to_write.setText(_translate("Controller", "/home/chenyu/MA/position.txt"))
        self.pbtnWriteCurrRobotPose.setText(_translate("Controller", "Write Current Pose to a File"))
        self.pbtnSaveHome.setText(_translate("Controller", "Save Home"))
        self.pbtnSaveOut.setText(_translate("Controller", "Save Out"))
        self.pbtnGoHome.setText(_translate("Controller", "GoHome"))
        self.pbtnGoOut.setText(_translate("Controller", "GoOut"))
        self.pbtnConnect.setText(_translate("Controller", "Connect"))
        self.pbtnDisconnect.setText(_translate("Controller", "Disconnect"))
        self.ledt_full_path_to_imf.setPlaceholderText(_translate("Controller", "Full path to an .imf file"))
        self.pbtnLoadSweep_imf.setText(_translate("Controller", "Load imf sweep"))
        self.pbtn_test_rotation.setText(_translate("Controller", "Test Rotation"))
        self.pbtnAddPoint.setText(_translate("Controller", "Add Point"))
        self.pbtnInitROS.setText(_translate("Controller", "Initialize ROS"))
        self.pbtnStopUSStream.setText(_translate("Controller", "Stop US Stream"))
        self.ledtSliceIndex.setPlaceholderText(_translate("Controller", "Index in Sweep"))
        self.pbtnComputerConfiMap.setText(_translate("Controller", "Compute Confi Map"))
        self.label_2.setText(_translate("Controller", "Select multiple positions and store them to finally move along them"))
        self.lblPosAngle.setText(_translate("Controller", "Ang(rad)"))
        self.lblPosZ.setText(_translate("Controller", "Z"))
        self.lblPosRa.setText(_translate("Controller", "Ra"))
        self.lblPosY.setText(_translate("Controller", "Y"))
        self.lblPosDistance.setText(_translate("Controller", "Pos(mm)"))
        self.lblPosX.setText(_translate("Controller", "X"))
        self.lblPosRb.setText(_translate("Controller", "Rb"))
        self.lblPosRc.setText(_translate("Controller", "Rc"))
        self.pbtnExcuteCmd.setText(_translate("Controller", "Excute Cmd"))
        self.chbRecordWrench.setText(_translate("Controller", "Record Wrench"))
        self.chbUpdateState.setText(_translate("Controller", "Update"))
        self.pbtnExecuteTrajectory.setText(_translate("Controller", "Execute Trajectory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Controller", "TestFunction"))
        self.label.setText(_translate("Controller", "Initial start angle of Fan motion:"))
        self.pbtnGoFanStart.setText(_translate("Controller", "Move to Initial Pose of Fan Motion"))
        self.cmbFanStartRotationAxis.setCurrentText(_translate("Controller", "Rotation X"))
        self.cmbFanStartRotationAxis.setItemText(0, _translate("Controller", "Rotation X"))
        self.cmbFanStartRotationAxis.setItemText(1, _translate("Controller", "Rotation Y"))
        self.cmbFanMotionType.setItemText(0, _translate("Controller", "Continous Fan Motion"))
        self.cmbFanMotionType.setItemText(1, _translate("Controller", "Step Fan Motion"))
        self.cmbRotationAxis.setItemText(0, _translate("Controller", "Rotation X"))
        self.cmbRotationAxis.setItemText(1, _translate("Controller", "Rotation Y"))
        self.cmbRotationStep.setItemText(0, _translate("Controller", "1 degree"))
        self.cmbRotationStep.setItemText(1, _translate("Controller", "2 degree"))
        self.cmbRotationStep.setItemText(2, _translate("Controller", "3 degree"))
        self.cmbRotationStep.setItemText(3, _translate("Controller", "4 degree"))
        self.cmbRotationStep.setItemText(4, _translate("Controller", "5 degree"))
        self.pbtnFanMotion.setText(_translate("Controller", "Fan Motion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Controller", "TaskFunction"))
        self.ledt_poses_file_path.setText(_translate("Controller", "/home/chenyu/MA/route.txt"))
        self.ledtSweepPath.setPlaceholderText(_translate("Controller", "Full Path to Sweep"))
        self.ledtDownsamplingParam.setText(_translate("Controller", "5"))
        self.ledtDownsamplingParam.setPlaceholderText(_translate("Controller", "Select every n frame"))
        self.pbtnDownsampleSweep.setText(_translate("Controller", "Downsample US Sweep"))
        self.pbtnForceMode.setText(_translate("Controller", "Force Mode"))
        self.pbtnPositionMode.setText(_translate("Controller", "Postion Mode"))
        self.ledtMainDir.setPlaceholderText(_translate("Controller", "Path to main dir"))
        self.pbtnCreateUSForLabelsWithoutStich.setText(_translate("Controller", "Create US Sweep For Labels"))
        self.pbtnContinueScan.setText(_translate("Controller", "Back to Break Point and Continue Scanning"))
        self.pbtnExecScan.setText(_translate("Controller", "Execute US Scan"))
        self.pbtnGoIntiPos.setText(_translate("Controller", "Move to Initial Position"))
        self.pbtnReadPosesFromFile.setText(_translate("Controller", "Load Poses"))
        self.lblStiffness.setText(_translate("Controller", "Stifness"))
        self.lblSesiredForce.setText(_translate("Controller", "Desired Force"))
        self.rbtn_no_fine_tuning.setText(_translate("Controller", "No fine Tuning"))
        self.rbtn_fine_tuning_1.setText(_translate("Controller", "Fine tuning 1"))
        self.rbtn_both_fine_tunings.setText(_translate("Controller", "Both"))
        self.checkBox_include_whole_sweep.setText(_translate("Controller", "Include whole sweep"))
        self.ledtDataDir.setPlaceholderText(_translate("Controller", "Data Dir"))
        self.pbtn_stitching.setText(_translate("Controller", "Stitching"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VisionControl), _translate("Controller", "VisionControl"))
        self.pbtnSavePose.setText(_translate("Controller", "Save current pose"))
        self.pbtnRoutePlanning.setText(_translate("Controller", "Route Planning"))
        self.pbtnPrepareForScan.setText(_translate("Controller", "Prepare for scan"))
        self.pbtnRunUSScan.setText(_translate("Controller", "Run US Scan"))
        self.ledtSweepFilePath.setText(_translate("Controller", "/home/robotics-verse/projects/chenyu/chest.imf"))
        self.pbtnLoadSweepPosition.setText(_translate("Controller", "Load and save sweep position"))
        self.pbtnLoadSweepImage.setText(_translate("Controller", "Load and save sweep images"))
        self.pbtnShowSurface.setText(_translate("Controller", "Show surface img"))
        self.pbtnExtractBoneSurface.setText(_translate("Controller", "Extract bone surface"))
        self.pbtbGetUSPointCloud.setText(_translate("Controller", "Get point cloud"))
        self.pbtnReplaceWithLabel.setText(_translate("Controller", "Replace With Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.US_preprocessing), _translate("Controller", "US_preprocessing"))

